### PR TITLE
Bump version to 2016.2.0 and enable build for Python 3

### PR DESCRIPTION
**Pull request by johannesring**

### CODE REVIEW

**Comment by oseledets** [comment]
Any updates on this?

**Comment by johannesring** [comment]
@oseledets - the problem is that some of the dependencies are not available for Python 3.6 yet. I am working on resolving this issue.

**Comment by oseledets** [comment]
@johannesring Thanks! The Python 2 recipe is working already? Sorry for a stupid question, how can I use it?

**Comment by johannesring** [comment]
@oseledets - no, not the latest version of dolfin-adjoint, but I guess the previous version (2016.1) works.

**Pull request merged**
